name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d5b0efc4b1b688b8c5dfdd6d8e33c1c04b021659b56fc49fa0c144ba385a69"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.16"
