name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16bdb268cba463c90adb81ace3b7fa19a919a91cecf175f84d14dfe475b233a8"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.16"
