name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfeef05870be9fe2d5b744234db6b87fe74b64629de37116d0f782ec18388e45"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.16"
