name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c576762090180e870691a28ce9fadc540ad7b337c2888512fc0ac9d2d9b2a745"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
