name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8f24cde3e3c4f953cec11b442e5fa3ed678ff11e70ec49a36c1af959509c2fd"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
