name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc60ad4c8b7c64c0ffc1e25df860068b7869850b2a4b8443a2fa7920f350971b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
