name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6491ae4c73cbfcbcf88179453542b0499fb8141cc1e1f0d48a58c3fbfe5ea9d"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.16"
